# Generated by Django 4.2.2 on 2023-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
